version: "3.7"

services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    volumes:
      - ./src/backend/:/app/:rw # для правки кода без перезагрузки
      - /etc/localtime:/etc/localtime/:ro
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      DEV_MODE: ${DEV_MODE}
    restart: always
    ports:
      - 2222:2222
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    restart: always
    hostname: db
    ports:
      - 5432:5432
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  server:
    build:
      context: ./src/nginx
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime/:ro
    ports:
      - ${FRONT_PORT}:80
    restart: always
